Vagrant.configure("2") do |config|
  
  # Box base: Rocky Linux 9
  config.vm.box = "generic/rocky9"
  
  # Nombre de la VM
  config.vm.hostname = "hpc-platform"

  # Recursos de la VM
  config.vm.provider "virtualbox" do |vb|
    vb.name   = "hpc-selfservice-platform"
    vb.memory = 6144   # 6GB RAM
    vb.cpus   = 4      # 4 núcleos
  end

  # Red: acceso a las UIs desde el host
  config.vm.network "forwarded_port", guest: 2746, host: 2746   # Argo Workflows
  config.vm.network "forwarded_port", guest: 8080, host: 8080   # ArgoCD
  config.vm.network "forwarded_port", guest: 30000, host: 30000 # Portal web

  # Carpeta compartida entre Windows y la VM
  config.vm.synced_folder "../", "/home/vagrant/project"

  # Script de aprovisionamiento
  config.vm.provision "shell", path: "provision.sh"

end